### PR TITLE
Fixes input masking problem

### LINKED ISSUE #100: Fix the input masking problem
cc @miguelcobain

### PR DESCRIPTION
**Pull request by martndemus**
Fixes #100

### CODE REVIEW

File: addon/components/one-way-input.js [hunk 1]
```diff
@@ -7,7 +7,8 @@ const {
   assert,
   get,
   set,
-  run
+  run,
+  run: { next }
```
Comment (rwjblue) [inline addon/components/one-way-input.js]: Should schedule for afterRender, no need to wait for next tick
